# Form implementation generated from reading ui file 'src/agepy/interactive/fitting/labeldialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LabelDialog(object):
    def setupUi(self, LabelDialog):
        LabelDialog.setObjectName("LabelDialog")
        LabelDialog.resize(400, 223)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LabelDialog.sizePolicy().hasHeightForWidth())
        LabelDialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        LabelDialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(LabelDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupXLabel = QtWidgets.QGroupBox(parent=LabelDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupXLabel.sizePolicy().hasHeightForWidth())
        self.groupXLabel.setSizePolicy(sizePolicy)
        self.groupXLabel.setObjectName("groupXLabel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupXLabel)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.editXLabel = QtWidgets.QLineEdit(parent=self.groupXLabel)
        self.editXLabel.setObjectName("editXLabel")
        self.horizontalLayout.addWidget(self.editXLabel)
        self.verticalLayout.addWidget(self.groupXLabel)
        self.groupYLabel = QtWidgets.QGroupBox(parent=LabelDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupYLabel.sizePolicy().hasHeightForWidth())
        self.groupYLabel.setSizePolicy(sizePolicy)
        self.groupYLabel.setObjectName("groupYLabel")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupYLabel)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.editYLabel = QtWidgets.QLineEdit(parent=self.groupYLabel)
        self.editYLabel.setObjectName("editYLabel")
        self.horizontalLayout_2.addWidget(self.editYLabel)
        self.verticalLayout.addWidget(self.groupYLabel)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=LabelDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(LabelDialog)
        self.buttonBox.accepted.connect(LabelDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(LabelDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LabelDialog)

    def retranslateUi(self, LabelDialog):
        _translate = QtCore.QCoreApplication.translate
        LabelDialog.setWindowTitle(_translate("LabelDialog", "Set Axes Labels"))
        self.groupXLabel.setTitle(_translate("LabelDialog", "xlabel"))
        self.groupYLabel.setTitle(_translate("LabelDialog", "ylabel"))
